server:
  port: 4646

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smash
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:hinatazaka46/smash/repository/mybatis/*.xml